### ISSUE TITLE
Script error?

### ISSUE THREAD

**Issue by Citizen-K** [bashcode/post-engintron-install#1]
`UnboundLocalError: local variable 'domconf' referenced before assignment`

All sites dead until SSL port is reverted to 443.

Seems to create the vhost and ssl folders in nginx but no changes are made to default.conf to reflect the paths.

**Comment by bashcode** [comment]
Please send me output of this command.

tree /etc/nginx

**Comment by Citizen-K** [comment]
root@arsa [~]# tree /etc/nginx

/etc/nginx

├── conf.d

│   ├── default.conf

│   ├── default.conf.bak

│   └── default.conf.rpmsave

├── custom_rules

├── custom_rules.dist

├── fastcgi_params

├── koi-utf

├── koi-win

├── mime.types

├── mime.types.bak

├── mime.types.rpmsave

├── modules -> ../../usr/lib64/nginx/modules

├── nginx.conf

├── nginx.conf.bak

├── nginx.conf.rpmsave

├── proxy_params_common

├── proxy_params_common.bak

├── proxy_params_dynamic

├── proxy_params_dynamic.bak

├── proxy_params_static

├── proxy_params_static.bak

├── scgi_params

├── scripts

│   ├── build-ssl-vhosts

│   └── fix-ssl.py

├── ssl.cert.d

│   ├── airgunsports.org.za_key -> /var/cpanel/ssl/installed/keys/cc386_f15b7_47e6727353af8cbe395ad659d6c74123.key

│   ├── airgunsports.org.za_SSL_cert

│   ├── airrifle.co.za_key -> /var/cpanel/ssl/installed/keys/c6893_c6061_479d1664546f6c5a9fa0ffda360342ad.key

│   └── airrifle.co.za_SSL_cert

├── uwsgi_params

├── vhost.ssl.d

│   ├── airgunsp

│   │   └── airgunsports.org.za_SSL.conf

│   ├── airgunsp.conf

│   ├── airrifle

│   │   └── airrifle.co.za_SSL.conf

│   ├── airrifle.conf

│   └── airrifleorg

├── vhosts.ssl.conf

└── win-utf

**Comment by bashcode** [comment]
Hello,

Please download the script again and try install now.
Script working on server with 200 cpanel users under SSL

cd /usr/local/src
git clone https://github.com/bashcode/post-engintron-install.git
cd post-engintron-install
sh install.sh -install

**Comment by Citizen-K** [comment]
Same error and lockout. Perhaps my server config is incompatible somehow.

Am I understanding the script function correctly; is it not supposed to also put the key/cert paths into default.conf?

**Comment by bashcode** [comment]
**First step**: Change apache SSL port to 1443, nginx working with port 443
**Second step**: Create configuration file for all cpanel users in directorio  /etc/nginx/vhost.ssl.d/
**Third step**: make a directory in /etc/nginx/ssl.cert.d with SSL pem config (cert,ca and key) in one file.
**Fourth step**: include SSL config in nginx.conf - include /etc/nginx/vhost.ssl.d/*.conf;

**The output of script**:

=== Building SSL vhost for all cpanel users ===
[+] Generating vhost for domainone.com_SSL ..
[+] Generating vhost for domaintwo.net_SSL ..
[+] Generating vhost for subdomain.domaintwo.net_SSL ..
[+] Generating vhost for domain4.cl_SSL ..
[+] Generating vhost for support.domain4.cl_SSL ..
[+] Generating vhost for domain5.bid_SSL ..
[+] Generating vhost for sub.domain5.bid_SSL ..


**NOTE**: It should be noted that no file is modified in engintron, except for nginx.conf to include the path of the SSL configuration


The script working in latest version of cpanel and engintron, with easyapache 3 and 4.
engintron is not compatible with cpanel PHP-FPM.

**Comment by Citizen-K** [comment]
Thanks for your patience and explanation. I did not think to look in nginx.conf for the added paths, they are there. I do not have  PHP-FPM compiled. For whatever reason all sites my server go dead with Apache on port 1443. 

With regret I have uninstalled Engintron, I will reconsider it once it is ready for prime time SSL.

**Comment by bashcode** [comment]
I can support you with teamviewer if you need help.

Regards
